### ISSUE TITLE
gamv.out is not generated [Ubuntu 18.04]

### ISSUE THREAD

**Issue by farliz** [GeostatsGuy/GeostatsPy#26]
Hi, 
When I execute GSLIB.gamv_2d  following error appears:
`FileNotFoundError: [Errno 2] No such file or directory: 'gamv.out'`

The path of the executables of the  GSLIB library is given at the first line. Other files gamv.par, 
gamv_out.dat are generated correctly.

It does not gamv.out file generated properly?

My code:

`nlag= 100; lagdist=100; azi=90; atol=22.2; bstand=100`

`lag_p, vario_p, nppiso_p = GSLIB.gamv_2d(data, 'X', 'Y', 'SBS', nlag, lagdist, azi, atol, bstand)`

**Comment by GeostatsGuy** [comment]
Howdy,

Please replace with the geostats.gamv command.  The referenced command utilizes GSLIB gamv.exe (that must be in the working directory).

o. GSLIB.* algorithms access the FORTRAN GSLIB.

Hope this helps,

Michael

MICHAEL J. PYRCZ, Ph.D., P.Eng.,  Associate Professor
The University of Texas at Austin  |  512-471-3252  |  www.pge.utexas.edu<http://www.pge.utexas.edu/>
Twitter<https://twitter.com/GeostatsGuy> (@GeostatsGuy) | LinkedIn<https://www.linkedin.com/in/michael-pyrcz-61a648a1/> | Webpage<http://www.michaelpyrcz.com/> | Book<https://www.amazon.com/Geostatistical-Reservoir-Modeling-Michael-Pyrcz/dp/0199731446> | GoogleScholar<https://scholar.google.com/citations?user=QVZ20eQAAAAJ&hl=en>

**Comment by farliz** [comment]
It works now! thanks

**Comment by OrlandoOP** [comment]
> It works now! thanks

Hi Farliz,

I am struggle with this error gamv_2d. May you let me know how did you solve it, please.
