### ISSUE TITLE
How to generate myself "variogram"?

### ISSUE THREAD

**Issue by cui-xiaoang96** [GeostatsGuy/GeostatsPy#27]
Thanks for your outsstanding work to help understanding and apply GeoStatistic.

And I want to make myself variogram to adapt my work and what should I do?

Or could you tell me the meaning of parameters about functions "make_variogram"?
I can not know the explain for th function.
![图片](https://user-images.githubusercontent.com/41711907/90026073-72383b80-dce9-11ea-868d-d2fd4dfdd426.png)

Thanks for your any help! 
Wish your reply.

**Comment by cui-xiaoang96** [comment]
And what should I do to use myself variogram to the funcation "sisim'?

Thanks for your help!

**Comment by WenPann** [comment]
I think you can find the detailed definitions for the input variables and
its usage from the manual of GSLIB, this module is a preprocessor for
GSLIB. Learning some basics about geostats may also help.

Regards,
Wen

*Wen Pan*

*Graduate Research Assistant | *The Joint Industry Research Consortium on
Formation Evaluation <https://faculty.engr.utexas.edu/formation> | Digital
Reservoir Characterization Technology
<https://github.com/GeostatsGuy/DIRECT>  | Bureau of Economic Geology

*Department of Petroleum and Geosystems Engineering               *

*The University of Texas at Austin*

*Mobile: (737) 484-6022*

**Comment by PauloCarvalhoRJ** [comment]
Hello, friend,

   You can take a look at GSLib's book which has been released publicly: http://claytonvdeutsch.com/wp-content/uploads/2019/03/GSLIB-Book-Second-Edition.pdf .  Refer to Chapter III.  It has some background and parameter explanation.  I hope this helps.  If you're unable to bootstrap yourself with that, I recommend reading a geostatistics primer.

regards,

Paulo

**Comment by cui-xiaoang96** [comment]
> 
> 
> Hello, friend,
> 
> You can take a look at GSLib's book which has been released publicly: http://claytonvdeutsch.com/wp-content/uploads/2019/03/GSLIB-Book-Second-Edition.pdf . Refer to Chapter III. It has some background and parameter explanation. I hope this helps. If you're unable to bootstrap yourself with that, I recommend reading a geostatistics primer.
> 
> regards,
> 
> Paulo

Thank you so much.

I will read it.

I wish you all the best
